import { z } from "zod";
import {
  zId,
  zIsoDate,
  zIsoDateTime,
  zYearMonth,
  zCents,
  newId,
  yearMonthOf,
} from "./primitives";

/** §5.4 transactions — unified ledger (expense/income, transfer, template, pending). */
export const InboxStatusSchema = z.enum(["pending", "approved"]);
export type InboxStatus = z.infer<typeof InboxStatusSchema>;

export const TransactionSchema = z
  .object({
    id: zId,
    date: zIsoDate,
    // Signed integer cents: negative = outflow, positive = inflow. Sign is a UI
    // default only — NOT coupled to category type here (§5.4 / §10.13), so voids,
    // reversals, and refunds can legitimately carry the opposite sign.
    amount: zCents,
    vendor_source: z.string().min(1), // for transfers: synthesized "{src} → {dest}", editable
    category_id: zId.nullable(), // null only for transfers
    container_id: zId, // source container / the account
    to_container_id: zId.nullable(), // set only for transfers — destination
    is_template: z.boolean(), // true = saved shortcut, not a live ledger entry
    template_name: z.string().nullable(),
    inbox_status: InboxStatusSchema, // 'pending' rows excluded from all derivations
    recurring_rule_id: zId.nullable(),
    notes: z.string().nullable(),
    // Void mechanism (M2, design decision — spec §5.4 has no correction field, §10 #24):
    // set ONLY on a reversing row → the id of the transaction it cancels. Both rows
    // remain in the ledger (append-only §0.3), balance stays exact; "X is voided" is
    // derived as "some row has reverses_id === X.id". Null for ordinary rows.
    reverses_id: zId.nullable(),
    // When this row was WRITTEN (M11). `date` is the calendar day the money moved
    // — user-chosen and backdatable — so it can't order the entries inside a day:
    // three things logged this afternoon share one `date` and used to tie-break on
    // a random UUID. This is the wall clock, taken from the authoring op's `ts` so
    // the row and the journal always agree. Null = a row written before M11 (or by
    // an older client); `sortForRegister` sinks those to the end of their day.
    entered_at: zIsoDateTime.nullable(),
    yearMonth: zYearMonth, // STORED, derived from `date` at write time (§8.3)
  })
  .refine((t) => t.yearMonth === t.date.slice(0, 7), {
    // A derived field can drift only through a hand-built payload or a future
    // writer — and a row whose yearMonth disagrees with its date vanishes from
    // every month-scoped read (§8.3, §10 #15). Catch it at the edge.
    message: "yearMonth must be derived from date",
    path: ["yearMonth"],
  });
export type Transaction = z.infer<typeof TransactionSchema>;

/**
 * Build an expense/income transaction (§5.4 shape: `category_id` set,
 * `to_container_id` null). Signed integer cents — sign is the caller's (the UI
 * pre-signs by category type, §10 #13). `yearMonth` is derived from `date` here
 * so the compound indexes can key on it (§8.3).
 */
export function makeTransaction(input: {
  date: string;
  amount: number; // signed cents
  vendor_source: string;
  category_id: string;
  id?: string;
  container_id?: string; // defaults to the caller-supplied general wallet
  inbox_status?: InboxStatus;
  recurring_rule_id?: string | null; // set on rows generated by a recurring rule (M6)
  notes?: string | null;
  entered_at?: string | null; // the writing instant; commands pass the op's `ts`
}): Transaction {
  return TransactionSchema.parse({
    id: input.id ?? newId(),
    date: input.date,
    amount: input.amount === 0 ? 0 : input.amount, // normalize -0
    vendor_source: input.vendor_source,
    category_id: input.category_id,
    container_id: input.container_id ?? "general",
    to_container_id: null,
    is_template: false,
    template_name: null,
    inbox_status: input.inbox_status ?? "approved",
    recurring_rule_id: input.recurring_rule_id ?? null,
    notes: input.notes ?? null,
    reverses_id: null,
    entered_at: input.entered_at ?? null,
    yearMonth: yearMonthOf(input.date),
  });
}

/**
 * Build a template (§5.8) — a saved 1-tap shortcut, NOT a live ledger entry
 * (`is_template = true`, excluded from every balance/report by `isLiveLedgerRow`).
 * Quick-logging one produces an ordinary `makeTransaction`/`makeTransfer` row.
 * A template can be an expense/income (has a category) or a transfer (has a
 * destination) — same shape rules as a real row. Amount is signed for the
 * expense/income shape and a positive magnitude for a transfer (matching the two
 * generators). `date` is a placeholder anchor — a template has no place on the
 * calendar; the real row is dated when logged.
 */
export function makeTemplate(input: {
  template_name: string;
  amount: number;
  vendor_source: string;
  container_id: string;
  category_id?: string | null;
  to_container_id?: string | null;
  id?: string;
  date?: string;
  notes?: string | null;
  entered_at?: string | null;
}): Transaction {
  const isTransfer = input.to_container_id != null;
  if (isTransfer === (input.category_id != null)) {
    throw new Error(
      "a template is either an expense/income (category) or a transfer (destination)",
    );
  }
  const date = input.date ?? "2000-01-01";
  return TransactionSchema.parse({
    id: input.id ?? newId(),
    date,
    amount: input.amount === 0 ? 0 : input.amount, // normalize -0
    vendor_source: input.vendor_source,
    category_id: input.category_id ?? null,
    container_id: input.container_id,
    to_container_id: input.to_container_id ?? null,
    is_template: true,
    template_name: input.template_name,
    inbox_status: "approved",
    recurring_rule_id: null,
    notes: input.notes ?? null,
    reverses_id: null,
    entered_at: input.entered_at ?? null,
    yearMonth: yearMonthOf(date),
  });
}

/**
 * Build the reversing row that voids `original` (§0.3 — never a destructive
 * delete). Same fields, opposite-sign `amount`, `reverses_id` → the original's
 * id. Dated `on` (defaults to the original's date) so it lands in a sensible
 * period; balance nets to zero across the pair.
 */
export function makeVoidRow(
  original: Transaction,
  opts?: { id?: string; on?: string; entered_at?: string | null },
): Transaction {
  // A template is a shortcut, not a ledger entry (§5.4) — there is nothing to
  // reverse, and the "reversal" would itself be a template. Remove it instead.
  if (original.is_template) {
    throw new Error("a template is not a ledger entry — remove it instead of voiding");
  }
  const date = opts?.on ?? original.date;
  return TransactionSchema.parse({
    ...original,
    id: opts?.id ?? newId(),
    date,
    amount: original.amount === 0 ? 0 : -original.amount,
    reverses_id: original.id,
    // A reversal is a NEW event, so it must NOT inherit the original's instant —
    // otherwise deleting something logged last week would file the reversal back
    // there, and an undo would sort behind edits made since (§1.1: the journal
    // shows the delete and the undo as their own moments).
    entered_at: opts?.entered_at ?? null,
    yearMonth: yearMonthOf(date),
  });
}

/** The synthesized transfer payee (§5.4) — keeps `vendor_source` NOT NULL with
 * no friction, and stays user-editable afterwards. */
export function transferLabel(fromName: string, toName: string): string {
  return `${fromName} → ${toName}`;
}

/**
 * Build a transfer (§5.4 shape: `category_id` null, `to_container_id` set).
 * A transfer is a SINGLE row keyed to the **source** container and stored
 * **negative** (§10 #5); the destination is credited via `to_container_id` in the
 * balance identity (§0.4). Callers pass a positive magnitude — signing is not
 * theirs to get wrong. Transfers carry no category, so they never touch the
 * expense/income dashboards; they are the contribution primitive (§5.6).
 */
export function makeTransfer(input: {
  date: string;
  amount: number; // positive magnitude in cents
  container_id: string; // source
  to_container_id: string; // destination
  fromName?: string; // used to synthesize vendor_source
  toName?: string;
  vendor_source?: string; // explicit label wins over the synthesized one
  id?: string;
  inbox_status?: InboxStatus;
  recurring_rule_id?: string | null; // set on rows generated by a recurring rule (M6)
  notes?: string | null;
  entered_at?: string | null;
}): Transaction {
  if (!Number.isSafeInteger(input.amount) || input.amount <= 0) {
    throw new Error("transfer amount must be a positive integer-cents magnitude");
  }
  if (input.container_id === input.to_container_id) {
    throw new Error("a transfer needs two different containers");
  }
  // A label of spaces would satisfy NOT NULL while telling the user nothing, so
  // blank falls back to the synthesized "{src} → {dest}" (§5.4).
  const given = input.vendor_source?.trim();
  const label =
    given && given.length > 0
      ? given
      : input.fromName && input.toName
        ? transferLabel(input.fromName, input.toName)
        : undefined;
  if (!label) throw new Error("transfer needs a vendor_source or both container names");

  return TransactionSchema.parse({
    id: input.id ?? newId(),
    date: input.date,
    amount: -input.amount, // outflow on the source container
    vendor_source: label,
    category_id: null, // transfers are category-less by definition
    container_id: input.container_id,
    to_container_id: input.to_container_id,
    is_template: false,
    template_name: null,
    inbox_status: input.inbox_status ?? "approved",
    recurring_rule_id: input.recurring_rule_id ?? null,
    notes: input.notes ?? null,
    reverses_id: null,
    entered_at: input.entered_at ?? null,
    yearMonth: yearMonthOf(input.date),
  });
}
