"use client";

import { useMemo, useState } from "react";
import { useAtomValue, useSetAtom } from "jotai";
import { toast } from "sonner";
import {
  ArrowRightIcon,
  CheckIcon,
  MoreHorizontalIcon,
  PencilIcon,
  Trash2Icon,
} from "lucide-react";
import {
  categoriesAtom,
  containersAtom,
  dispatchAtom,
  readyAtom,
  transactionsAtom,
} from "@/features/store";
import { approveTransaction, unvoidTransaction, voidTransaction } from "@/core/commands";
import { isTransfer } from "@/core/engine/balances";
import { pendingRows } from "@/core/engine/ledger";
import { formatCents } from "@/core/money";
import type { Transaction } from "@/core/model";
import { cn } from "@/lib/utils";
import { categoryDotColor } from "@/features/category-color";
import { EditTransactionSheet } from "@/features/ledger/EditTransactionSheet";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

const dayFormat = new Intl.DateTimeFormat("en-US", {
  month: "short",
  day: "numeric",
  year: "numeric",
});
const formatDay = (iso: string) => dayFormat.format(new Date(iso + "T00:00:00"));

/**
 * The Pending / Inbox queue (§5.8). Rows generated by recurring rules land here
 * and move no money until approved — so nothing here counts toward any balance or
 * report. 1-tap approve, multi-select bulk approve, edit-before-approving, and a
 * dismiss (a void, undoable) for occurrences the user doesn't want.
 */
export function InboxView() {
  const ready = useAtomValue(readyAtom);
  const transactions = useAtomValue(transactionsAtom);
  const categories = useAtomValue(categoriesAtom);
  const containers = useAtomValue(containersAtom);
  const dispatch = useSetAtom(dispatchAtom);

  const [editing, setEditing] = useState<Transaction | null>(null);
  const [selected, setSelected] = useState<Set<string>>(new Set());

  const pending = useMemo(
    () =>
      pendingRows(transactions).sort((a, b) =>
        a.date < b.date ? -1 : a.date > b.date ? 1 : a.id < b.id ? -1 : 1,
      ),
    [transactions],
  );

  const nameOf = useMemo(() => {
    const m = new Map(categories.map((c) => [c.id, c.name]));
    return (id: string | null) => (id ? (m.get(id) ?? "Unknown") : "Transfer");
  }, [categories]);
  const containerNameOf = useMemo(() => {
    const m = new Map(containers.map((c) => [c.id, c.name]));
    return (id: string | null) => (id ? (m.get(id) ?? "Unknown") : "");
  }, [containers]);

  // Keep the selection to rows that still exist in the queue.
  const liveSelection = useMemo(() => {
    const ids = new Set(pending.map((t) => t.id));
    return new Set([...selected].filter((id) => ids.has(id)));
  }, [selected, pending]);
  const allChecked = pending.length > 0 && liveSelection.size === pending.length;

  function toggle(id: string) {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }
  function toggleAll() {
    setSelected(allChecked ? new Set() : new Set(pending.map((t) => t.id)));
  }

  async function approve(ids: string[]) {
    for (const id of ids) await dispatch(approveTransaction(id));
    setSelected(new Set());
    toast.success(ids.length === 1 ? "Approved" : `Approved ${ids.length}`);
  }

  async function dismiss(t: Transaction) {
    const op = voidTransaction(t);
    await dispatch(op);
    if (editing?.id === t.id) setEditing(null);
    const voidRow = op.type === "transaction.void" ? op.payload.row : null;
    toast.success("Dismissed", {
      description: `${t.vendor_source} · ${formatCents(t.amount)}`,
      action: voidRow
        ? {
            label: "Undo",
            onClick: () => {
              void dispatch(unvoidTransaction(voidRow)).then(() =>
                toast.success("Back in the inbox", { description: t.vendor_source }),
              );
            },
          }
        : undefined,
    });
  }

  if (!ready) return <p className="text-muted-foreground py-16 text-sm">Loading…</p>;

  return (
    <div className="space-y-6">
      <section className="pt-3 pb-1">
        <p className="text-muted-foreground text-xs font-medium tracking-[0.18em] uppercase">
          Inbox
        </p>
        <h1 className="font-display mt-1 text-3xl leading-none">
          {pending.length === 0 ? "All clear" : `${pending.length} to review`}
        </h1>
        <p className="text-muted-foreground mt-3 text-sm">
          Recurring transactions wait here until you approve them. Nothing counts toward a
          balance until it does.
        </p>
      </section>

      {liveSelection.size > 0 && (
        <div className="border-primary/20 bg-primary/[0.06] sticky top-2 z-10 flex items-center gap-3 rounded-2xl border px-4 py-2.5">
          <span className="text-sm font-medium">{liveSelection.size} selected</span>
          <Button
            size="sm"
            className="ml-auto rounded-full"
            onClick={() => approve([...liveSelection])}
          >
            <CheckIcon className="size-4" />
            Approve selected
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="text-muted-foreground rounded-full"
            onClick={() => setSelected(new Set())}
          >
            Clear
          </Button>
        </div>
      )}

      <div className="bg-card overflow-hidden rounded-2xl border">
        {pending.length === 0 ? (
          <div className="text-muted-foreground px-5 py-14 text-center text-sm">
            Nothing to review. Recurring rules will drop their due transactions here.
          </div>
        ) : (
          <>
            <div className="text-muted-foreground bg-muted/30 flex items-center gap-3 px-5 py-2 text-xs font-medium">
              <Checkbox
                checked={allChecked}
                onCheckedChange={toggleAll}
                aria-label="Select all"
              />
              <span>Select all</span>
            </div>
            {pending.map((t, i) => (
              <InboxRow
                key={t.id}
                tx={t}
                checked={liveSelection.has(t.id)}
                onCheck={() => toggle(t.id)}
                categoryName={nameOf(t.category_id)}
                containerName={containerNameOf(t.container_id)}
                toContainerName={containerNameOf(t.to_container_id)}
                divider={i > 0}
                onApprove={() => approve([t.id])}
                onEdit={() => setEditing(t)}
                onDismiss={() => dismiss(t)}
              />
            ))}
          </>
        )}
      </div>

      <EditTransactionSheet
        editing={editing}
        categories={categories}
        containers={containers}
        onOpenChange={(open) => !open && setEditing(null)}
        onSave={async (op) => {
          await dispatch(op);
          setEditing(null);
          toast.message("Saved — still pending", {
            description: "Approve it below to make it live.",
          });
        }}
        onDelete={dismiss}
      />
    </div>
  );
}

function InboxRow({
  tx,
  checked,
  onCheck,
  categoryName,
  containerName,
  toContainerName,
  divider,
  onApprove,
  onEdit,
  onDismiss,
}: {
  tx: Transaction;
  checked: boolean;
  onCheck: () => void;
  categoryName: string;
  containerName: string;
  toContainerName: string;
  divider: boolean;
  onApprove: () => void;
  onEdit: () => void;
  onDismiss: () => void;
}) {
  const transfer = isTransfer(tx);
  const income = !transfer && tx.amount >= 0;
  const sub = transfer
    ? [containerName || "Transfer", toContainerName].filter(Boolean).join(" → ")
    : [categoryName, containerName].filter(Boolean).join(" · ");

  return (
    <div
      className={cn(
        "group hover:bg-muted/40 flex items-center gap-3 px-5 py-3 transition-colors",
        divider && "border-t",
      )}
    >
      <Checkbox
        checked={checked}
        onCheckedChange={onCheck}
        aria-label={`Select ${tx.vendor_source}`}
      />
      {transfer ? (
        <ArrowRightIcon className="text-muted-foreground size-2.5 shrink-0" aria-hidden />
      ) : (
        <span
          className="size-2.5 shrink-0 rounded-full"
          style={{
            backgroundColor: tx.category_id
              ? categoryDotColor(tx.category_id)
              : undefined,
          }}
          aria-hidden
        />
      )}
      <div className="min-w-0 flex-1">
        <div className="truncate text-sm font-medium">{tx.vendor_source}</div>
        <div className="text-muted-foreground truncate text-xs">
          {formatDay(tx.date)} · {sub}
        </div>
      </div>
      <div
        className={cn(
          "tnum font-mono text-sm tracking-tight",
          income && "text-positive",
          transfer && "text-muted-foreground",
        )}
      >
        {transfer ? formatCents(Math.abs(tx.amount)) : formatCents(tx.amount)}
      </div>
      <Button
        size="sm"
        variant="ghost"
        className="text-positive hover:text-positive hover:bg-positive/10 rounded-full"
        onClick={onApprove}
        aria-label={`Approve ${tx.vendor_source}`}
      >
        <CheckIcon className="size-4" />
        Approve
      </Button>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button
            variant="ghost"
            size="icon"
            className="text-muted-foreground size-8 rounded-lg opacity-0 transition-opacity group-hover:opacity-100 focus-visible:opacity-100 data-[state=open]:opacity-100"
            aria-label="Pending transaction actions"
          >
            <MoreHorizontalIcon className="size-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onClick={onEdit}>
            <PencilIcon className="size-4" />
            Edit before approving
          </DropdownMenuItem>
          <DropdownMenuItem variant="destructive" onClick={onDismiss}>
            <Trash2Icon className="size-4" />
            Dismiss
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}
