"use client";

import { useMemo, useState } from "react";
import { useAtomValue, useSetAtom } from "jotai";
import { toast } from "sonner";
import {
  ArrowRightIcon,
  CheckIcon,
  InboxIcon,
  PencilIcon,
  Trash2Icon,
} from "lucide-react";
import {
  categoriesAtom,
  containersAtom,
  dispatchAtom,
  readyAtom,
  recurringRulesAtom,
  transactionsAtom,
} from "@/features/store";
import { approveTransaction, unvoidTransaction, voidTransaction } from "@/core/commands";
import { isTransfer } from "@/core/engine/balances";
import { activeFilterCount, applyFilter, isFilterActive } from "@/core/engine/filter";
import { isRegisterSort, pendingRows, sortRegister } from "@/core/engine/ledger";
import { formatCents } from "@/core/money";
import type { Transaction } from "@/core/model";
import { cn } from "@/lib/utils";
import { categoryColor, categoryColorFor } from "@/features/category-color";
import { NO_FILTER, toFilter, type FilterDraft } from "@/features/filter-draft";
import { useLocalPref } from "@/features/prefs";
import { EditTransactionSheet } from "@/features/ledger/EditTransactionSheet";
import { FilterBar } from "@/features/FilterBar";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { DropdownMenuItem } from "@/components/ui/dropdown-menu";
import {
  EmptyState,
  ListSkeleton,
  Money,
  PageHeader,
  PageHeaderSkeleton,
  RowActions,
} from "@/features/ui";

const dayFormat = new Intl.DateTimeFormat("en-US", {
  month: "short",
  day: "numeric",
  year: "numeric",
});
const formatDay = (iso: string) => dayFormat.format(new Date(iso + "T00:00:00"));

/** Device-local: how you like to READ the queue, not a fact about your money. */
const SORT_KEY = "yaccount.inbox.sort";

/** The queue's own default is oldest-first — the thing that came due first is
 *  the thing to deal with first. The orders themselves are the register's, so
 *  the two screens can't drift apart. */
const SORT_OPTIONS = [
  { value: "oldest", label: "Oldest" },
  { value: "newest", label: "Newest" },
  { value: "largest", label: "Largest" },
  { value: "smallest", label: "Smallest" },
] as const;

/**
 * The Pending / Inbox queue (§5.8). Rows generated by recurring rules land here
 * and move no money until approved — so nothing here counts toward any balance or
 * report. 1-tap approve, multi-select bulk approve, edit-before-approving, and a
 * dismiss (a void, undoable) for occurrences the user doesn't want.
 *
 * These ARE transactions, so the rail narrows them through `matchesFilter` — the
 * same predicate the register and the ⌘K palette use (M11 phase 6). One extra
 * question the ledger never asks: which rule proposed the row.
 */
export function InboxView() {
  const ready = useAtomValue(readyAtom);
  const transactions = useAtomValue(transactionsAtom);
  const categories = useAtomValue(categoriesAtom);
  const containers = useAtomValue(containersAtom);
  const rules = useAtomValue(recurringRulesAtom);
  const dispatch = useSetAtom(dispatchAtom);

  const [editing, setEditing] = useState<Transaction | null>(null);
  const [selected, setSelected] = useState<Set<string>>(new Set());

  // Sort is remembered; the filters are deliberately not (§12.4 M11).
  const [sort, setSort] = useLocalPref(SORT_KEY, "oldest", isRegisterSort);
  const [draft, setDraft] = useState<FilterDraft>(NO_FILTER);
  const filter = useMemo(() => toFilter(draft), [draft]);
  const filtering = isFilterActive(filter);

  const pending = useMemo(() => pendingRows(transactions), [transactions]);

  const nameOf = useMemo(() => {
    const m = new Map(categories.map((c) => [c.id, c.name]));
    return (id: string | null) => (id ? (m.get(id) ?? "Unknown") : "Transfer");
  }, [categories]);
  const dotOf = useMemo(
    () => (id: string | null) => (id ? categoryColorFor(id, categories) : undefined),
    [categories],
  );
  const containerNameOf = useMemo(() => {
    const m = new Map(containers.map((c) => [c.id, c.name]));
    return (id: string | null) => (id ? (m.get(id) ?? "Unknown") : "");
  }, [containers]);

  // What else a row can be found by: the engine keeps no lookup tables, so the
  // view that has the names hands them over.
  const labelOf = useMemo(
    () => (t: Transaction) =>
      `${nameOf(t.category_id)} ${containerNameOf(t.container_id)} ${containerNameOf(t.to_container_id)}`,
    [nameOf, containerNameOf],
  );

  const rows = useMemo(
    () => sortRegister(applyFilter(pending, filter, { label: labelOf }), sort),
    [pending, filter, labelOf, sort],
  );

  // Only rules that actually proposed something waiting here — a facet listing
  // rules with nothing pending is a menu of dead ends.
  const ruleOptions = useMemo(() => {
    const waiting = new Set(
      pending.map((t) => t.recurring_rule_id).filter((id): id is string => id !== null),
    );
    return rules
      .filter((r) => waiting.has(r.id))
      .map((r) => ({ value: r.id, label: r.template_vendor_source }))
      .sort((a, b) => a.label.localeCompare(b.label));
  }, [pending, rules]);

  // A selection is over what you can SEE. Narrowing the filter drops the rows it
  // hides out of the selection, so "Approve selected" can never act on something
  // that isn't on the screen.
  const liveSelection = useMemo(() => {
    const ids = new Set(rows.map((t) => t.id));
    return new Set([...selected].filter((id) => ids.has(id)));
  }, [selected, rows]);
  const allChecked = rows.length > 0 && liveSelection.size === rows.length;

  function toggle(id: string) {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }
  function toggleAll() {
    setSelected(allChecked ? new Set() : new Set(rows.map((t) => t.id)));
  }

  async function approve(ids: string[]) {
    for (const id of ids) await dispatch(approveTransaction(id));
    setSelected(new Set());
    toast.success(ids.length === 1 ? "Approved" : `Approved ${ids.length}`);
  }

  // Dismiss one or many pending rows (each a void, undoable). Undo un-dismisses
  // every row in the batch, restoring them to the inbox.
  async function dismissMany(rows: Transaction[]) {
    if (rows.length === 0) return;
    const voidRows: Transaction[] = [];
    for (const t of rows) {
      const op = voidTransaction(t);
      await dispatch(op);
      if (op.type === "transaction.void") voidRows.push(op.payload.row);
    }
    if (rows.some((t) => t.id === editing?.id)) setEditing(null);
    setSelected(new Set());
    toast.success(rows.length === 1 ? "Dismissed" : `Dismissed ${rows.length}`, {
      description:
        rows.length === 1
          ? `${rows[0].vendor_source} · ${formatCents(rows[0].amount)}`
          : undefined,
      action: {
        label: "Undo",
        onClick: () => {
          void Promise.all(voidRows.map((v) => dispatch(unvoidTransaction(v)))).then(() =>
            toast.success(
              voidRows.length === 1
                ? "Back in the inbox"
                : `${voidRows.length} back in the inbox`,
            ),
          );
        },
      },
    });
  }

  const dismiss = (t: Transaction) => dismissMany([t]);

  if (!ready)
    return (
      <div className="space-y-6">
        <PageHeaderSkeleton />
        <div className="bg-card overflow-hidden rounded-2xl border">
          <ListSkeleton rows={4} />
        </div>
      </div>
    );

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Inbox"
        title={pending.length === 0 ? "All clear" : `${pending.length} to review`}
      >
        Recurring transactions wait here until you approve them. Nothing counts toward a
        balance until it does.
      </PageHeader>

      {pending.length > 0 && (
        <FilterBar
          search={draft.text}
          onSearch={(text) => setDraft((d) => ({ ...d, text }))}
          searchPlaceholder="Search pending"
          facets={[
            {
              id: "rule",
              label: "Rule",
              selected: draft.ruleIds,
              onChange: (ruleIds) => setDraft((d) => ({ ...d, ruleIds })),
              options: ruleOptions,
            },
            {
              id: "container",
              label: "Wallet",
              selected: draft.containerIds,
              onChange: (containerIds) => setDraft((d) => ({ ...d, containerIds })),
              options: containers
                .filter((c) => !c.is_archived)
                .map((c) => ({ value: c.id, label: c.name })),
            },
            {
              id: "category",
              label: "Category",
              selected: draft.categoryIds,
              onChange: (categoryIds) => setDraft((d) => ({ ...d, categoryIds })),
              options: categories
                .filter((c) => !c.is_archived)
                .map((c) => ({
                  value: c.id,
                  label: c.name,
                  dot: categoryColor(c),
                })),
            },
          ]}
          ranges={[
            {
              label: "Date",
              type: "date",
              from: draft.dates.from,
              to: draft.dates.to,
              active: Boolean(draft.dates.from || draft.dates.to),
              onChange: (dates) => setDraft((d) => ({ ...d, dates })),
            },
          ]}
          sort={{ value: sort, options: [...SORT_OPTIONS], onChange: setSort }}
          activeCount={activeFilterCount(filter)}
          onClear={() => setDraft(NO_FILTER)}
        />
      )}

      {/* Sticky UNDER the top bar (`sticky top-0 h-14 z-30`), not at the very
          top where it would slide beneath it. The labels are short and the row
          wraps, because at 390px "Approve selected · Dismiss · Clear" ran off
          the screen and took the page's horizontal scroll with it (§12.4). */}
      {liveSelection.size > 0 && (
        <div className="border-primary/20 bg-primary/[0.06] sticky top-16 z-20 flex flex-wrap items-center gap-2 rounded-2xl border px-4 py-2.5">
          <span className="text-sm font-medium">{liveSelection.size} selected</span>
          <div className="ml-auto flex items-center gap-1">
            <Button
              size="sm"
              className="rounded-full"
              onClick={() => approve([...liveSelection])}
            >
              <CheckIcon className="size-4" />
              Approve
            </Button>
            <Button
              size="sm"
              variant="ghost"
              className="text-muted-foreground hover:text-destructive rounded-full"
              onClick={() => dismissMany(rows.filter((t) => liveSelection.has(t.id)))}
            >
              <Trash2Icon className="size-4" />
              Dismiss
            </Button>
            <Button
              size="sm"
              variant="ghost"
              className="text-muted-foreground rounded-full"
              onClick={() => setSelected(new Set())}
            >
              Clear
            </Button>
          </div>
        </div>
      )}

      <div className="bg-card overflow-hidden rounded-2xl border">
        {rows.length === 0 ? (
          filtering && pending.length > 0 ? (
            <EmptyState
              title="Nothing matches those filters"
              action={
                <Button
                  variant="outline"
                  size="sm"
                  className="rounded-full"
                  onClick={() => setDraft(NO_FILTER)}
                >
                  Clear filters
                </Button>
              }
            >
              {pending.length} {pending.length === 1 ? "row is" : "rows are"} waiting —
              widen the filters to see them.
            </EmptyState>
          ) : (
            <EmptyState icon={InboxIcon} title="Nothing to review">
              Recurring rules drop their due transactions here, and you decide what
              actually happened.
            </EmptyState>
          )
        ) : (
          <>
            <div className="text-muted-foreground bg-muted/30 flex items-center gap-3 px-5 py-2 text-xs font-medium">
              <Checkbox
                checked={allChecked}
                onCheckedChange={toggleAll}
                aria-label="Select all"
              />
              <span>{filtering ? `Select these ${rows.length}` : "Select all"}</span>
            </div>
            {rows.map((t, i) => (
              <InboxRow
                key={t.id}
                tx={t}
                checked={liveSelection.has(t.id)}
                onCheck={() => toggle(t.id)}
                dot={dotOf(t.category_id)}
                categoryName={nameOf(t.category_id)}
                containerName={containerNameOf(t.container_id)}
                toContainerName={containerNameOf(t.to_container_id)}
                divider={i > 0}
                onApprove={() => approve([t.id])}
                onEdit={() => setEditing(t)}
                onDismiss={() => dismiss(t)}
              />
            ))}
          </>
        )}
      </div>

      <EditTransactionSheet
        editing={editing}
        categories={categories}
        containers={containers}
        onOpenChange={(open) => !open && setEditing(null)}
        onSave={async (op) => {
          await dispatch(op);
          setEditing(null);
          toast.message("Saved — still pending", {
            description: "Approve it below to make it live.",
          });
        }}
        onDelete={dismiss}
      />
    </div>
  );
}

function InboxRow({
  tx,
  checked,
  onCheck,
  dot,
  categoryName,
  containerName,
  toContainerName,
  divider,
  onApprove,
  onEdit,
  onDismiss,
}: {
  tx: Transaction;
  checked: boolean;
  onCheck: () => void;
  /** The category's colour (override or auto), resolved by the parent. */
  dot: string | undefined;
  categoryName: string;
  containerName: string;
  toContainerName: string;
  divider: boolean;
  onApprove: () => void;
  onEdit: () => void;
  onDismiss: () => void;
}) {
  const transfer = isTransfer(tx);
  const income = !transfer && tx.amount >= 0;
  const sub = transfer
    ? [containerName || "Transfer", toContainerName].filter(Boolean).join(" → ")
    : [categoryName, containerName].filter(Boolean).join(" · ");

  return (
    <div
      className={cn(
        // Tighter gaps below `sm`: this row carries a checkbox and an approve
        // control the register hasn't got, and at 390px those 20px are the
        // difference between a readable payee and three characters of one.
        "group hover:bg-muted/40 active:bg-muted/60 flex items-center gap-2 px-5 py-3 transition-colors duration-[var(--dur-1)] ease-[var(--ease-register)] sm:gap-3",
        divider && "border-t",
      )}
    >
      <Checkbox
        checked={checked}
        onCheckedChange={onCheck}
        aria-label={`Select ${tx.vendor_source}`}
      />
      {transfer ? (
        <ArrowRightIcon className="text-muted-foreground size-2.5 shrink-0" aria-hidden />
      ) : (
        <span
          className="size-2.5 shrink-0 rounded-full"
          style={{ backgroundColor: dot }}
          aria-hidden
        />
      )}
      <div className="min-w-0 flex-1">
        <div className="truncate text-sm font-medium">{tx.vendor_source}</div>
        <div className="text-muted-foreground truncate text-xs">
          {formatDay(tx.date)} · {sub}
        </div>
      </div>
      <Money
        cents={tx.amount}
        absolute={transfer}
        tone={transfer ? "quiet" : income ? "in" : "neutral"}
        className="text-sm tracking-tight"
      />
      {/* The word costs 55px a row, and a phone hasn't got it — the check mark
          and the aria-label carry the meaning below `sm`. */}
      <Button
        size="sm"
        variant="ghost"
        className="text-positive hover:text-positive hover:bg-positive/10 shrink-0 rounded-full px-2 sm:px-3"
        onClick={onApprove}
        aria-label={`Approve ${tx.vendor_source}`}
      >
        <CheckIcon className="size-4" />
        <span className="hidden sm:inline">Approve</span>
      </Button>
      <RowActions label={`Actions for ${tx.vendor_source}`}>
        <DropdownMenuItem onClick={onEdit}>
          <PencilIcon className="size-4" />
          Edit before approving
        </DropdownMenuItem>
        <DropdownMenuItem variant="destructive" onClick={onDismiss}>
          <Trash2Icon className="size-4" />
          Dismiss
        </DropdownMenuItem>
      </RowActions>
    </div>
  );
}
